[package]
name = "rustcli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rustcli"
path = "src/main.rs"

[dependencies]
reqwest = { version = "0.12", features = ["blocking"] }
tokio = { version = "1", features = ["full"] }
